// Generated by scripts/sync_languages.py; edit languages.json.
module.exports = {
  "zh": "中文",
  "en": "English",
  "ja": "日本語",
  "ko": "한국어",
  "fr": "Français",
  "de": "Deutsch",
  "es": "Español",
  "ru": "Русский",
  "pt": "Português",
  "ar": "العربية"
};
