"""Generate a native mini-program JS module from the shared language catalog."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / "miniprogram/config/languages.json").read_text(encoding="utf-8"))
output = "// Generated by scripts/sync_languages.py; edit languages.json.\nmodule.exports = "
output += json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"
(ROOT / "miniprogram/config/languages.js").write_text(output, encoding="utf-8")
